name: Release Plugin

concurrency: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The projectVersion found in gradle.properties file'
        required: true
      publishToMarketPlace:
        description: 'Publish to JetBrains Marketplace?'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew buildPlugin
      - name: Publish Plugin to JetBrains Marketplace
        if: ${{ inputs.publishToMarketPlace == 'true' }}
        env:
          PUBLISH_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
        run: |
          ./gradlew publishPlugin -Pchannel=stable
          echo "Published ${{ inputs.version }} to the JetBrains Marketplace"
      - name: Create Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ inputs.version }} \
            --title "${{ inputs.version }}" \
            --generate-notes
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.version }} ./build/distributions/*
